### ISSUE TITLE
what does c_dim mean in the code

### ISSUE THREAD

**Issue by yzyhlzj** [xinyandai/gradient-quantization#3]
what does c_dim mean in the code below?  and function of " self.dim = self.dim // 2 * 3"?thx

        if c_dim == 0 or self.size < args.c_dim:
            self.dim = self.size
        else:
            self.dim = c_dim
            for i in range(0, 10):
                if size % self.dim != 0:
                    self.dim = self.dim // 2 * 3

**Comment by yzyhlzj** [comment]
the code above is in qsgd

**Comment by xinyandai** [comment]
* **c_dim**: for QSGD and HSQ, when the dimension of gradient vector is high, we quantize the gradient **segment by segment**, i.e., split the high dimensional vector into multiple low dimensional vectors, where** c_dim** is the dimension of such segment/low dimensional vector. Please refer ```section 4  QSGD Variants```.
* However, for a specific network, a fixed **c_dim** may not be divisible by all gradient dimensions (all layers of netwoek), the ```else part``` is ugly and it is just one way to adjust **c_dim** to make it divisible (since the number of parameters in convolutional layers is always divisible by 3). You may remove it and assign a specific **c_dim** for each layer.

Hope this help:)

**Comment by yzyhlzj** [comment]
> * **c_dim**: for QSGD and HSQ, when the dimension of gradient vector is high, we quantize the gradient **segment by segment**, i.e., split the high dimensional vector into multiple low dimensional vectors, where** c_dim** is the dimension of such segment/low dimensional vector. Please refer `section 4  QSGD Variants`.
> * However, for a specific network, a fixed **c_dim** may not be divisible by all gradient dimensions (all layers of netwoek), the `else part` is ugly and it is just one way to adjust **c_dim** to make it divisible (since the number of parameters in convolutional layers is always divisible by 3). You may remove it and assign a specific **c_dim** for each layer.
> 
> Hope this help:)

Thanks for replying, this is very helpful 👍
